### ISSUE TITLE
Bot crashed with the message: "A request to the Telegram API was unsuccessful. Error code: 502 Description: Bad Gateway"

### ISSUE THREAD

**Issue by midnightdim** [eternnoir/pyTelegramBotAPI#983]
> 1. What version of pyTelegramBotAPI are you using?

3.7.3

> 2. What OS are you using?

Debian 4.9.189-3+deb9u2

> 3. What version of python are you using?

3.5.3

Bot unexpectedly crashed with the following message (and stopped working):
"A request to the Telegram API was unsuccessful. Error code: 502 Description: Bad Gateway"

Seems like there was a solution for this case here: 
https://github.com/eternnoir/pyTelegramBotAPI/pull/223

But apparently it doesn't seem to work in the version that I have.

**Comment by BLUE-DEVIL1134** [comment]
hey,
i have been through the same error before!

just show the codes of the bots to see what's the error..

u might have used some wrong tags  of html and used the parse_mode="html"

**Comment by midnightdim** [comment]
Based on the error above it doesn't seem to be related to the code of the bot. It couldn't reach Telegram API and crashed.
The bot has been working for a couple of days then it crashed with this error (and it hasn't been used at all).

**Comment by BLUE-DEVIL1134** [comment]
oh
this sometimes happens when no request is made to the bot for a long time...

**Comment by goldenrump** [comment]
you use pooling or webhook?

If that pooling, try this - 
[eternnoir/pyTelegramBotAPI#34 (comment)](https://github.com/eternnoir/pyTelegramBotAPI/issues/34#issuecomment-121278432) 

If webhook, try to change secret key.

**Comment by midnightdim** [comment]
Pooling. Thanks, going to try that.

**Comment by Badiboy** [comment]
You posted no code, so nobody knows how you run bot.

Just make exception handling around polling.
Or use infinity_polling instead of polling.

**Comment by goldenrump** [comment]
> You posted no code, so nobody knows how you run bot.
> 
> Just make exception handling around polling.
> Or use infinity_polling instead of polling.

5 days have passed since his reply to me. I think his problem is solved and you can close it.

**Comment by midnightdim** [comment]
> You posted no code, so nobody knows how you run bot.

I was using standard bot.polling().

Then changed to:
```
bot.set_update_listener(listener) #register listener
bot.polling(True)
```

as suggested above. 

The bot still crashes. Now the error is:
```
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 334, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1236, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by Badiboy** [comment]
In the above (https://github.com/eternnoir/pyTelegramBotAPI/issues/983#issuecomment-706699601) there was:

> Just make exception handling around polling.
> Or use infinity_polling instead of polling.

**Comment by midnightdim** [comment]
@Badiboy I was editing the comment - I switched to infinity_polling already, thanks. If it crashes I'll let you know.

**Comment by midnightdim** [comment]
OK, it works with infinity_polling, sometimes it throws this exception (and keeps working):
 ```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 104, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
```

So perhaps can be marked as closed.
